#!/usr/bin/env bash

set -euo pipefail

DOTBOT_DIR='.dotbot'
DOTBOT_BIN='bin/dotbot'
CONFIG='install.conf.yaml'

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${BASEDIR}"

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

dotbot_install() {
	echo -e "\e[1mInstalling profile "${1}"\e[0m"
	"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}/${1}" -c "${BASEDIR}/${1}/${CONFIG}"
}

dotbot_install common
