
[bell]
color = "#005FA5"
duration = 100

[colors.bright]
black = "#2e3436"
blue = "#729fcf"
cyan = "#34e2e2"
green = "#8ae234"
magenta = "#ad7fa8"
red = "#ef2929"
white = "#eeeeec"
yellow = "#fce94f"

[colors.cursor]
cursor = "#ff0000"
text = "#ffffff"

[colors.normal]
black = "#2e3436"
blue = "#3465a4"
cyan = "#06989a"
green = "#73d216"
magenta = "#75507b"
red = "#cc0000"
white = "#d3d7cf"
yellow = "#edd400"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 14.0

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Light"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "ExtraBold"

[font.offset]
x = 0
y = -3

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"

[[keyboard.bindings]]
chars = "\u0002"
key = 127

[[keyboard.bindings]]
chars = "\u0002y"
key = "T"
mods = "Shift|Control"

[[keyboard.bindings]]
chars = "\u0002k"
key = "K"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mods = "Shift|Control|Alt"

[window.dimensions]
columns = 140
lines = 35

[general]
ipc_socket = false
