# Homebrew
if [ -e /home/linuxbrew ]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
elif [ -e ~/.linuxbrew ]; then
  eval "$(~/.linuxbrew/bin/brew shellenv)"
fi

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
if [ -e "${PYENV_ROOT}" ]; then
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init --path)"
fi
